# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

#
# THIS DIRECTORY NEEDS TO BE CHANGED LOCALLY FOR MIGRATIONS TO RUN
# TO AUTOMATICALLY GENERATE THIS FILE WITH YOUR LOCAL PATH, RUN:
#   npm run generate-toml   or   python set_diesel_toml
#
[migrations_directory]
dir = "/home/ahaider/repos/chamber/migrations"

