name: 'Backend Unit Tests'

on:
  push:
    branches:
      - main
    paths:
      - 'src-tauri/**'
  pull_request:
    paths:
      - 'src-tauri/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: npm install
      
      - name: Run setup to bundle ffmpeg and yt-dlp
        run: npm run setup

      - name: Run unit tests
        run: cargo test
        working-directory: src-tauri
