name: Rust Tests

on:
  pull_request:
    paths:
      - 'src-tauri/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libsoup2.4-dev \
            libssl-dev \
            pkg-config \
            libclang-dev \
            build-essential

      - name: Set up Rust
        uses: actions-rs/toolchain@v2
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache Cargo registry, index, and build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build and run tests
        run: cargo test --all --verbose
        working-directory: src-tauri
